#!groovy
pipeline {
   agent {
       label 'built-in' // machine name
    }
    tools {
        maven 'Default'
    }
    options {
        skipDefaultCheckout true 
    }
    stages {
    	stage('Checkout Repository'){
    		steps{
					checkout scm
    		}		
    	}
    	stage('Build') {
    		steps{
        		sh "rm -rf .git"
                sh "mvn --version"
            }
        }
        stage('Test') {
        	steps{
        		script {
        		    	def props = readProperties file: 'devops/src/main/resources/application.properties'
        				sh "mvn -f devops/pom.xml clean test -DAccesskey==${Accesskeyid} -DSecretkey=${Secretkeyid}"
           		}
           	}
        }
	}
}
		